name: release

on: 
  push:
    branches:
      - main

jobs:
  qa:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: '0'
    - name: go vorbereiten
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: './go.mod'
    - name: impulsar vorbereiten
      uses: aimotrens/impulsar@main
    - name: Tests ausführen
      run: |
        impulsar run qa


  tag-next-version:
    permissions:
      contents: write
    needs: qa
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.version }}
      hasNextVersion: ${{ steps.get_next_version.outputs.hasNextVersion }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: '0'
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@main
      with:
        prefix: 'v'
    - name: Create tag
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        git tag ${{ steps.get_next_version.outputs.version }}
        git push origin ${{ steps.get_next_version.outputs.version }}


  build-gh-release:
    permissions:
      contents: write
    needs: tag-next-version
    if: ${{ needs.tag-next-version.outputs.hasNextVersion == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: go vorbereiten
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: './go.mod'
    - name: impulsar vorbereiten
      uses: aimotrens/impulsar@main
    - name: Build
      env:
        KTMPL_VERSION: ${{ needs.tag-next-version.outputs.version }}
      run: |
        impulsar run build pack-release
    - name: Github-Release erstellen
      uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
      with:
        artifacts: "release/artifacts/*"
        tag: ${{ needs.tag-next-version.outputs.version }}

        
  build-docker:
    permissions:
      contents: read
    needs: tag-next-version
    if: ${{ needs.tag-next-version.outputs.hasNextVersion == 'true' }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3

      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: KTMPL_VERSION=${{ needs.tag-next-version.outputs.version }}
          tags: ${{ secrets.REG_USER }}/kdeploy:${{ needs.tag-next-version.outputs.version }},${{ secrets.REG_USER }}/kdeploy:latest
